name: Basic Workflow

on:
 push:
   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: current directory
        run: pwd

      - name: long listing
        run: ls -l
      
      - name: show date
        run: date

   
     